CREATE table Players (PlayerID  int NOT NULL PRIMARY KEY,
               FirstName VARCHAR NOT NULL,
               LastName VARCHAR NOT NULL,
               Goals INT NOT NULL,
               Position VARCHAR NOT NULL,
               Nationality VARCHAR NOT NULL
               );
insert into Players VALUES (1,'Alan', 'Shearer',260,'Forward','England'),
                    (2,'Wayne', 'Rooney',208,'Forward', 'England'),
                    (3,'Andrew','Cole',187,'Forward ', 'England'),
                    (4,'Sergio', 'Aguero',180,'Forward','Argentina'),
                    (5,'Frank','Lampard',177,'Midfielder','England'),
                    (6,'Thierry','Henry',175,'Forward','France'),
                    (7,'Robbie', 'Fowler',163,'Forward','England'),
                    (8,'Jermain','Defoe',162,'Forward','England'),
                    (9,'Michael','Owen',150,'Forward','England'),
                    (10,'Les','Ferdinand',149,'Forward','England'),
                    (11,'Teddy','Sheringham',147,'Forward','England'),
                    (12,'Robin','van Persie',144,'Forward','Netherlands'),
                    (13,'Harry','Kane',136,'Forward','England'),
                    (14,'Jimmy Floyd','Hasselbaink',127,'Forward','Netherlands'),
                    (15,'Robbie','Keane',126,'Forward','Irish'),
                    (16,'Nicolas','Anelka',125,'Forward','France'),
                    (17,'Dwight','Yorke',123 ,'Forward','Trinidad and Tobago '),
                    (18,'Steven','Gerrard',120 ,'Midfielder','England'),
                    (19,'Romelu','Lukaku',113,'Forward','Belgium'),
                    (20,'Ian','Wright',113,'Forward','England'),
                    (21,'Dion','Dublin',111,'Forward','England'),
                    (22,'Emile','Heskey',110,'Forward','England'),
                    (23,'Ryan','Giggs',109,'Midfielder','Wales'),
                    (24,'Peter','Crouch',108,'Forward','England'),
                    (25,'Paul','Scholes',107,'Midfielder','England'),
                    (26,'Darren','Bent',106,'Forward','England'),
                    (27,'Didier','Drogba',104,'Forward','Ivory Coast'),
                    (28,'Matt','Le Tissier',102,'Attacking Midfielder','England'),
                    (29,'Jaime','Vardy',99,'Forward','England'),
                    (30,'Emmanuel','Adebayor',97,'Forward','Togo');
SELECT * FROM Players;             